spring.application.name=usuarios

spring.datasource.url=jdbc:postgresql://ep-jolly-forest-a4hn1jmr-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_DOr32IgmeUGC

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true